### PR TITLE
Fixes symbol order in I101 error message.

### PR DESCRIPTION
**Pull request by AndreLouisCaron**
Fixes issue #44.  The `should_be` variable was being sorted using lower-case string comparisons, which didn't match what the `is_sorted()` helper function checks.

### CODE REVIEW

**Comment by public** [comment]
Can you add a line to the CHANGELOG for this?

**Comment by AndreLouisCaron** [comment]
@public Will do.  However, I just noticed this in the changelog:

```
0.6.1
-----

 * Fixed a bug where I101 messages were not suggesting the correct order.
```

I took a look at the file's history and it looks like I'm effectively reverting PR #41.  I'm under the impression that this message should adapt to the import order style that's being used.  Is that the case?

**Comment by AndreLouisCaron** [comment]
OK, I added a pair of tests for the formatting of `I101` messages.  I also added a new changelog entry.  Lemme know if you want me to change anything!

**Comment by public** [comment]
Sigh. I am not good at programming sometimes.

This is great though, thanks a lot for the PR :)

**Comment by ashb** [comment]
:+1: Thanks for the fix! Any chance we could get this released to pypi?

**Pull request merged**
